DATA SEGMENT
MESSAGE DB "THIS IS THE STRING$"
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE,DS:DATA
START:MOV AX,DATA
MOV DS,AX
MOV AH,9 ; DOS FUNCTION #9
MOV DX,OFFSET MESSAGE ; OFFSET OF THE STRING
INT 21H ; DISPLAY IT
MOV Ah,4CH
INT 21H
CODE ENDS
END START
